plugins {
    id 'java'
    id 'org.springframework.boot' version '2.4.13' // use a early version
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

group GROUP_ID
version VERSION

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

jar.enabled = true
bootJar.enabled = false

sourceSets {
    test {
        java {
            srcDir 'src/test/java'
            srcDir 'build/generated/java'
        }
    }
}

dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
    implementation libs.slf4j.api

    implementation libs.jupiter.api
    implementation libs.junit.platform.commons
    testRuntimeOnly libs.jupiter.engine

    implementation libs.dreamcat.common

    compileOnly 'org.springframework.boot:spring-boot'
    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'

    testImplementation "org.springframework.boot:spring-boot"
    testImplementation "org.springframework.boot:spring-boot-autoconfigure"
    testImplementation "org.springframework.boot:spring-boot-test"
    testImplementation "org.springframework:spring-test"
    testImplementation libs.mockito.junit.jupiter

    testImplementation "org.springframework.boot:spring-boot-starter-web"
    testImplementation "org.springframework.boot:spring-boot-starter-jdbc"
}

test {
    useJUnitPlatform()
}

apply from: new File(rootDir, 'gradle/publish.gradle')
