# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
[versions]
dreamcat = "0.5-SNAPSHOT"
# https://mvnrepository.com/artifact/org.projectlombok/lombok
lombok = '1.18.30'
# https://mvnrepository.com/artifact/org.slf4j/slf4j-api
slf4j = '1.7.36'
# https://central.sonatype.com/artifact/org.junit.jupiter/junit-jupiter-api
jupiter = '5.9.2'
# https://central.sonatype.com/artifact/org.junit.platform/junit-platform-commons
junit-platform = '1.9.2'
# https://central.sonatype.com/artifact/org.mockito/mockito-junit-jupiter
mockito-jupiter = '5.9.0'

[libraries]
dreamcat-common = { module = "org.dreamcat:common", version.ref = "dreamcat" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
junit-platform-commons = { module = "org.junit.platform:junit-platform-commons", version.ref = "junit-platform"}
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito-jupiter" }
